services:
  api:
    image: ghcr.io/mourya2044/indipostcollect-backend:latest
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  web:
    image: ghcr.io/mourya2044/indipostcollect-frontend:latest
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/.env:/app/.env